# Generated by Django 5.2.5 on 2025-09-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0008_rodzajlokalu_alter_inwestycjazdjecie_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inwestycjazdjecie",
            options={},
        ),
        migrations.AlterModelOptions(
            name="rodzajlokalu",
            options={"verbose_name_plural": "Rodzaje Lokali"},
        ),
    ]
