# Generated by Django 5.2.5 on 2025-09-05 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0009_alter_inwestycjazdjecie_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rzut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obraz", models.ImageField(upload_to="rzuty/")),
                (
                    "oferta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rzuty",
                        to="oferty.oferta",
                    ),
                ),
            ],
        ),
    ]
