# Generated by Django 5.2.5 on 2025-09-05 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oferty", "0010_rzut"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rzut",
            old_name="obraz",
            new_name="zdjecie",
        ),
        migrations.AlterField(
            model_name="oferta",
            name="inwestycja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oferty",
                to="oferty.inwestycja",
            ),
        ),
    ]
